# 1. setup - mysql + redis - container
# 2. setup - nest
# 2.1 build - nest image
# 2.2 run - nest container

# but usually use when you have a lot of dependencies + we dont need to deplay mysql and redis and nest together

# run with `docker-compose up`

services:
  nest-app:
    build:
      context: ./
      dockerfile: ./v2.Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - '3000:3000'
  mysql-container:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - /Users/gtec/lwt/mysql-cache:/var/lib/mysql
  redis-container:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - /Users/gtec/lwt/docker-cache/redis-cache:/data
